Enable custom overlays
Change-Id: Ia934203e747b43aa4941ed906312966e38fbd841
Signed-off-by: Stephen Reaves <reaves735@gmail.com>

diff --git a/diskimage_builder/elements/gentoo/pre-install.d/02-gentoo-03-enable-overlays b/diskimage_builder/elements/gentoo/pre-install.d/02-gentoo-03-enable-overlays
--- a/diskimage_builder/elements/gentoo/pre-install.d/02-gentoo-03-enable-overlays
+++ b/diskimage_builder/elements/gentoo/pre-install.d/02-gentoo-03-enable-overlays
@@ -20,11 +20,21 @@ if [[ ${GENTOO_OVERLAYS} != '' ]]; then
     fi
 
     emerge ${GENTOO_EMERGE_DEFAULT_OPTS} --oneshot openssl openssh
+    USE="-http2 -http3 -quic -curl_quic_openssl" emerge ${GENTOO_EMERGE_DEFAULT_OPTS} --oneshot net-misc/curl
     emerge ${GENTOO_EMERGE_DEFAULT_OPTS} --oneshot eselect-repository
     # enable the various overlays, ignore failures (overlay my already be enabled)
     set +e
     for OVERLAY in ${GENTOO_OVERLAYS}; do
         eselect repository enable "${OVERLAY}"
+        emaint sync -r "${OVERLAY}"
+    done
+    set -e
+
+    # enable the various custom overlays, ignore failures (overlay my already be enabled)
+    set +e
+    for OVERLAY in ${GENTOO_CUSTOM_OVERLAYS}; do
+        eselect repository add $(echo "${OVERLAY}" | sed 's/:/ git /' )
+        emaint sync -r $(echo "${OVERLAY}" | sed 's/:.*//' )
     done
     set -e
 
